FROM nvidia/cuda:11.4.0-runtime-ubuntu18.04
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"


RUN apt-get update && apt-get install -y python3-dev wget


RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir root/.conda \
    && sh Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh

RUN conda create -y -n instanceGM

RUN conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch



COPY . src/

RUN /bin/bash -c "cd src\
    && source activate instanceGM \
    && pip3 install -r requirements.txt"



